language: r
r:
  - oldrel
  - release
  - devel

sudo: false

cache: packages

r_packages:
  - covr

branches:
  only:
    - master
    - development
    - rc
    - rdevel

after_success:
  - Rscript covr.R
