language: r
r:
  - release
  - devel

sudo: false

cache: packages

r_packages:
  - covr

branches:
  only:
    - master
    - development
    - rc
    - issue50

matrix:
  include:
    - r: 3.1
      branches: rc
    - r: 3.2
      branches: rc
    - r: 3.3
      branches: rc
    - r: oldrel
      branches: rc

after_success:
  - Rscript covr.R
